name: バグ報告
description: Modのバグを報告。一つのIssueにつき一つでお願いします
body:
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
    validations:
      required: true

  - type: input
    id: mod-version
    attributes:
      label: Mod Version
    validations:
      required: true

  - type: input
    id: log-file
    attributes:
      label: ログファイル
      description: よくわからない方はを[こちら](https://github.com/UKON256/UKONCore/wiki/latest.log%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)ご覧になってください
    validations:
      required: true

  - type: textarea
    attributes:
      label: 再現手順

  - type: textarea
    attributes:
      label: その他の情報

